apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name | default 'mypvc' }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .size | default '100Mi' }}
  storageClassName: {{ .sc-name | default 'default' }}

