apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name | default "my-pvc" }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .size | default "10Mi" }}
  storageClassName: {{ .sc-name | default "default" }}

